/* ============================================================
   Base R named colors (from grDevices colors()) and package
   color-scale helpers (viridis, RColorBrewer, scales).
   ============================================================ */

const BASE_COLORS = [
  { family: "Reds & Pinks", colors: [
    { name: "red", hex: "#FF0000" }, { name: "red1", hex: "#FF0000" }, { name: "red2", hex: "#EE0000" },
    { name: "red3", hex: "#CD0000" }, { name: "red4", hex: "#8B0000" }, { name: "darkred", hex: "#8B0000" },
    { name: "firebrick", hex: "#B22222" }, { name: "firebrick1", hex: "#FF3030" }, { name: "firebrick2", hex: "#EE2C2C" },
    { name: "firebrick3", hex: "#CD2626" }, { name: "firebrick4", hex: "#8B1A1A" },
    { name: "indianred", hex: "#CD5C5C" }, { name: "indianred1", hex: "#FF6A6A" }, { name: "indianred2", hex: "#EE6363" },
    { name: "indianred3", hex: "#CD5555" }, { name: "indianred4", hex: "#8B3A3A" },
    { name: "tomato", hex: "#FF6347" }, { name: "tomato1", hex: "#FF6347" }, { name: "tomato2", hex: "#EE5C42" },
    { name: "tomato3", hex: "#CD4F39" }, { name: "tomato4", hex: "#8B3626" },
    { name: "coral", hex: "#FF7F50" }, { name: "coral1", hex: "#FF7256" }, { name: "coral2", hex: "#EE6A50" },
    { name: "coral3", hex: "#CD5B45" }, { name: "coral4", hex: "#8B3E2F" },
    { name: "salmon", hex: "#FA8072" }, { name: "salmon1", hex: "#FF8C69" }, { name: "salmon2", hex: "#EE8262" },
    { name: "salmon3", hex: "#CD7054" }, { name: "salmon4", hex: "#8B4C39" },
    { name: "lightsalmon", hex: "#FFA07A" }, { name: "lightsalmon1", hex: "#FFA07A" }, { name: "lightsalmon2", hex: "#EE9572" },
    { name: "lightsalmon3", hex: "#CD8162" }, { name: "lightsalmon4", hex: "#8B5742" },
    { name: "darksalmon", hex: "#E9967A" }, { name: "lightcoral", hex: "#F08080" },
    { name: "hotpink", hex: "#FF69B4" }, { name: "hotpink1", hex: "#FF6EB4" }, { name: "hotpink2", hex: "#EE6AA7" },
    { name: "hotpink3", hex: "#CD6090" }, { name: "hotpink4", hex: "#8B3A62" },
    { name: "deeppink", hex: "#FF1493" }, { name: "deeppink1", hex: "#FF1493" }, { name: "deeppink2", hex: "#EE1289" },
    { name: "deeppink3", hex: "#CD1076" }, { name: "deeppink4", hex: "#8B0A50" },
    { name: "pink", hex: "#FFC0CB" }, { name: "pink1", hex: "#FFB5C5" }, { name: "pink2", hex: "#EEA9B8" },
    { name: "pink3", hex: "#CD919E" }, { name: "pink4", hex: "#8B636C" },
    { name: "lightpink", hex: "#FFB6C1" }, { name: "lightpink1", hex: "#FFAEB9" }, { name: "lightpink2", hex: "#EEA2AD" },
    { name: "lightpink3", hex: "#CD8C95" }, { name: "lightpink4", hex: "#8B5F65" },
    { name: "palevioletred", hex: "#DB7093" }, { name: "palevioletred1", hex: "#FF82AB" }, { name: "palevioletred2", hex: "#EE799F" },
    { name: "palevioletred3", hex: "#CD6889" }, { name: "palevioletred4", hex: "#8B475D" },
    { name: "violetred", hex: "#D02090" }, { name: "violetred1", hex: "#FF3E96" }, { name: "violetred2", hex: "#EE3A8C" },
    { name: "violetred3", hex: "#CD3278" }, { name: "violetred4", hex: "#8B2252" }, { name: "mediumvioletred", hex: "#C71585" },
    { name: "maroon", hex: "#B03060" }, { name: "maroon1", hex: "#FF34B3" }, { name: "maroon2", hex: "#EE30A7" },
    { name: "maroon3", hex: "#CD2990" }, { name: "maroon4", hex: "#8B1C62" },
    { name: "rosybrown", hex: "#BC8F8F" }, { name: "rosybrown1", hex: "#FFC1C1" }, { name: "rosybrown2", hex: "#EEB4B4" },
    { name: "rosybrown3", hex: "#CD9B9B" }, { name: "rosybrown4", hex: "#8B6969" },
    { name: "mistyrose", hex: "#FFE4E1" }, { name: "mistyrose1", hex: "#FFE4E1" }, { name: "mistyrose2", hex: "#EED5D2" },
    { name: "mistyrose3", hex: "#CDB7B5" }, { name: "mistyrose4", hex: "#8B7D7B" }, { name: "brown", hex: "#A52A2A" },
    { name: "brown1", hex: "#FF4040" }, { name: "brown2", hex: "#EE3B3B" }, { name: "brown3", hex: "#CD3333" }, { name: "brown4", hex: "#8B2323" },
  ]},
  { family: "Oranges & Browns", colors: [
    { name: "orange", hex: "#FFA500" }, { name: "orange1", hex: "#FFA500" }, { name: "orange2", hex: "#EE9A00" },
    { name: "orange3", hex: "#CD8500" }, { name: "orange4", hex: "#8B5A00" },
    { name: "darkorange", hex: "#FF8C00" }, { name: "darkorange1", hex: "#FF7F00" }, { name: "darkorange2", hex: "#EE7600" },
    { name: "darkorange3", hex: "#CD6600" }, { name: "darkorange4", hex: "#8B4500" },
    { name: "orangered", hex: "#FF4500" }, { name: "orangered1", hex: "#FF4500" }, { name: "orangered2", hex: "#EE4000" },
    { name: "orangered3", hex: "#CD3700" }, { name: "orangered4", hex: "#8B2500" },
    { name: "chocolate", hex: "#D2691E" }, { name: "chocolate1", hex: "#FF7F24" }, { name: "chocolate2", hex: "#EE7621" },
    { name: "chocolate3", hex: "#CD661D" }, { name: "chocolate4", hex: "#8B4513" },
    { name: "sienna", hex: "#A0522D" }, { name: "sienna1", hex: "#FF8247" }, { name: "sienna2", hex: "#EE7942" },
    { name: "sienna3", hex: "#CD6839" }, { name: "sienna4", hex: "#8B4726" },
    { name: "saddlebrown", hex: "#8B4513" }, { name: "sandybrown", hex: "#F4A460" }, { name: "peru", hex: "#CD853F" },
    { name: "tan", hex: "#D2B48C" }, { name: "tan1", hex: "#FFA54F" }, { name: "tan2", hex: "#EE9A49" },
    { name: "tan3", hex: "#CD853F" }, { name: "tan4", hex: "#8B5A2B" },
    { name: "burlywood", hex: "#DEB887" }, { name: "burlywood1", hex: "#FFD39B" }, { name: "burlywood2", hex: "#EEC591" },
    { name: "burlywood3", hex: "#CDAA7D" }, { name: "burlywood4", hex: "#8B7355" },
    { name: "bisque", hex: "#FFE4C4" }, { name: "bisque1", hex: "#FFE4C4" }, { name: "bisque2", hex: "#EED5B7" },
    { name: "bisque3", hex: "#CDB79E" }, { name: "bisque4", hex: "#8B7D6B" },
    { name: "navajowhite", hex: "#FFDEAD" }, { name: "navajowhite1", hex: "#FFDEAD" }, { name: "navajowhite2", hex: "#EECFA1" },
    { name: "navajowhite3", hex: "#CDB38B" }, { name: "navajowhite4", hex: "#8B795E" },
    { name: "peachpuff", hex: "#FFDAB9" }, { name: "peachpuff1", hex: "#FFDAB9" }, { name: "peachpuff2", hex: "#EECBAD" },
    { name: "peachpuff3", hex: "#CDAF95" }, { name: "peachpuff4", hex: "#8B7765" },
    { name: "wheat", hex: "#F5DEB3" }, { name: "wheat1", hex: "#FFE7BA" }, { name: "wheat2", hex: "#EED8AE" },
    { name: "wheat3", hex: "#CDBA96" }, { name: "wheat4", hex: "#8B7E66" },
    { name: "antiquewhite", hex: "#FAEBD7" }, { name: "antiquewhite1", hex: "#FFEFDB" }, { name: "antiquewhite2", hex: "#EEDFCC" },
    { name: "antiquewhite3", hex: "#CDC0B0" }, { name: "antiquewhite4", hex: "#8B8378" }, { name: "papayawhip", hex: "#FFEFD5" },
  ]},
  { family: "Yellows & Golds", colors: [
    { name: "yellow", hex: "#FFFF00" }, { name: "yellow1", hex: "#FFFF00" }, { name: "yellow2", hex: "#EEEE00" },
    { name: "yellow3", hex: "#CDCD00" }, { name: "yellow4", hex: "#8B8B00" },
    { name: "gold", hex: "#FFD700" }, { name: "gold1", hex: "#FFD700" }, { name: "gold2", hex: "#EEC900" },
    { name: "gold3", hex: "#CDAD00" }, { name: "gold4", hex: "#8B7500" },
    { name: "goldenrod", hex: "#DAA520" }, { name: "goldenrod1", hex: "#FFC125" }, { name: "goldenrod2", hex: "#EEB422" },
    { name: "goldenrod3", hex: "#CD9B1D" }, { name: "goldenrod4", hex: "#8B6914" },
    { name: "darkgoldenrod", hex: "#B8860B" }, { name: "darkgoldenrod1", hex: "#FFB90F" }, { name: "darkgoldenrod2", hex: "#EEAD0E" },
    { name: "darkgoldenrod3", hex: "#CD950C" }, { name: "darkgoldenrod4", hex: "#8B6508" },
    { name: "lightgoldenrod", hex: "#EEDD82" }, { name: "lightgoldenrod1", hex: "#FFEC8B" }, { name: "lightgoldenrod2", hex: "#EEDC82" },
    { name: "lightgoldenrod3", hex: "#CDBE70" }, { name: "lightgoldenrod4", hex: "#8B814C" }, { name: "lightgoldenrodyellow", hex: "#FAFAD2" },
    { name: "palegoldenrod", hex: "#EEE8AA" },
    { name: "khaki", hex: "#F0E68C" }, { name: "khaki1", hex: "#FFF68F" }, { name: "khaki2", hex: "#EEE685" },
    { name: "khaki3", hex: "#CDC673" }, { name: "khaki4", hex: "#8B864E" }, { name: "darkkhaki", hex: "#BDB76B" },
    { name: "lemonchiffon", hex: "#FFFACD" }, { name: "lemonchiffon1", hex: "#FFFACD" }, { name: "lemonchiffon2", hex: "#EEE9BF" },
    { name: "lemonchiffon3", hex: "#CDC9A5" }, { name: "lemonchiffon4", hex: "#8B8970" },
    { name: "cornsilk", hex: "#FFF8DC" }, { name: "cornsilk1", hex: "#FFF8DC" }, { name: "cornsilk2", hex: "#EEE8CD" },
    { name: "cornsilk3", hex: "#CDC8B1" }, { name: "cornsilk4", hex: "#8B8878" },
    { name: "lightyellow", hex: "#FFFFE0" }, { name: "lightyellow1", hex: "#FFFFE0" }, { name: "lightyellow2", hex: "#EEEED1" },
    { name: "lightyellow3", hex: "#CDCDB4" }, { name: "lightyellow4", hex: "#8B8B7A" }, { name: "moccasin", hex: "#FFE4B5" },
  ]},
  { family: "Greens", colors: [
    { name: "green", hex: "#00FF00" }, { name: "green1", hex: "#00FF00" }, { name: "green2", hex: "#00EE00" },
    { name: "green3", hex: "#00CD00" }, { name: "green4", hex: "#008B00" }, { name: "darkgreen", hex: "#006400" },
    { name: "forestgreen", hex: "#228B22" },
    { name: "seagreen", hex: "#2E8B57" }, { name: "seagreen1", hex: "#54FF9F" }, { name: "seagreen2", hex: "#4EEE94" },
    { name: "seagreen3", hex: "#43CD80" }, { name: "seagreen4", hex: "#2E8B57" }, { name: "mediumseagreen", hex: "#3CB371" },
    { name: "springgreen", hex: "#00FF7F" }, { name: "springgreen1", hex: "#00FF7F" }, { name: "springgreen2", hex: "#00EE76" },
    { name: "springgreen3", hex: "#00CD66" }, { name: "springgreen4", hex: "#008B45" }, { name: "mediumspringgreen", hex: "#00FA9A" },
    { name: "lawngreen", hex: "#7CFC00" },
    { name: "chartreuse", hex: "#7FFF00" }, { name: "chartreuse1", hex: "#7FFF00" }, { name: "chartreuse2", hex: "#76EE00" },
    { name: "chartreuse3", hex: "#66CD00" }, { name: "chartreuse4", hex: "#458B00" },
    { name: "greenyellow", hex: "#ADFF2F" }, { name: "yellowgreen", hex: "#9ACD32" },
    { name: "olivedrab", hex: "#6B8E23" }, { name: "olivedrab1", hex: "#C0FF3E" }, { name: "olivedrab2", hex: "#B3EE3A" },
    { name: "olivedrab3", hex: "#9ACD32" }, { name: "olivedrab4", hex: "#698B22" },
    { name: "darkolivegreen", hex: "#556B2F" }, { name: "darkolivegreen1", hex: "#CAFF70" }, { name: "darkolivegreen2", hex: "#BCEE68" },
    { name: "darkolivegreen3", hex: "#A2CD5A" }, { name: "darkolivegreen4", hex: "#6E8B3D" },
    { name: "limegreen", hex: "#32CD32" }, { name: "lightgreen", hex: "#90EE90" },
    { name: "palegreen", hex: "#98FB98" }, { name: "palegreen1", hex: "#9AFF9A" }, { name: "palegreen2", hex: "#90EE90" },
    { name: "palegreen3", hex: "#7CCD7C" }, { name: "palegreen4", hex: "#548B54" },
    { name: "darkseagreen", hex: "#8FBC8F" }, { name: "darkseagreen1", hex: "#C1FFC1" }, { name: "darkseagreen2", hex: "#B4EEB4" },
    { name: "darkseagreen3", hex: "#9BCD9B" }, { name: "darkseagreen4", hex: "#698B69" },
    { name: "mediumaquamarine", hex: "#66CDAA" },
    { name: "aquamarine", hex: "#7FFFD4" }, { name: "aquamarine1", hex: "#7FFFD4" }, { name: "aquamarine2", hex: "#76EEC6" },
    { name: "aquamarine3", hex: "#66CDAA" }, { name: "aquamarine4", hex: "#458B74" },
    { name: "honeydew", hex: "#F0FFF0" }, { name: "honeydew1", hex: "#F0FFF0" }, { name: "honeydew2", hex: "#E0EEE0" },
    { name: "honeydew3", hex: "#C1CDC1" }, { name: "honeydew4", hex: "#838B83" },
  ]},
  { family: "Blues", colors: [
    { name: "blue", hex: "#0000FF" }, { name: "blue1", hex: "#0000FF" }, { name: "blue2", hex: "#0000EE" },
    { name: "blue3", hex: "#0000CD" }, { name: "blue4", hex: "#00008B" }, { name: "darkblue", hex: "#00008B" },
    { name: "mediumblue", hex: "#0000CD" }, { name: "navy", hex: "#000080" }, { name: "midnightblue", hex: "#191970" },
    { name: "royalblue", hex: "#4169E1" }, { name: "royalblue1", hex: "#4876FF" }, { name: "royalblue2", hex: "#436EEE" },
    { name: "royalblue3", hex: "#3A5FCD" }, { name: "royalblue4", hex: "#27408B" },
    { name: "steelblue", hex: "#4682B4" }, { name: "steelblue1", hex: "#63B8FF" }, { name: "steelblue2", hex: "#5CACEE" },
    { name: "steelblue3", hex: "#4F94CD" }, { name: "steelblue4", hex: "#36648B" },
    { name: "dodgerblue", hex: "#1E90FF" }, { name: "dodgerblue1", hex: "#1E90FF" }, { name: "dodgerblue2", hex: "#1C86EE" },
    { name: "dodgerblue3", hex: "#1874CD" }, { name: "dodgerblue4", hex: "#104E8B" },
    { name: "deepskyblue", hex: "#00BFFF" }, { name: "deepskyblue1", hex: "#00BFFF" }, { name: "deepskyblue2", hex: "#00B2EE" },
    { name: "deepskyblue3", hex: "#009ACD" }, { name: "deepskyblue4", hex: "#00688B" },
    { name: "skyblue", hex: "#87CEEB" }, { name: "skyblue1", hex: "#87CEFF" }, { name: "skyblue2", hex: "#7EC0EE" },
    { name: "skyblue3", hex: "#6CA6CD" }, { name: "skyblue4", hex: "#4A708B" },
    { name: "lightskyblue", hex: "#87CEFA" }, { name: "lightskyblue1", hex: "#B0E2FF" }, { name: "lightskyblue2", hex: "#A4D3EE" },
    { name: "lightskyblue3", hex: "#8DB6CD" }, { name: "lightskyblue4", hex: "#607B8B" },
    { name: "lightblue", hex: "#ADD8E6" }, { name: "lightblue1", hex: "#BFEFFF" }, { name: "lightblue2", hex: "#B2DFEE" },
    { name: "lightblue3", hex: "#9AC0CD" }, { name: "lightblue4", hex: "#68838B" }, { name: "powderblue", hex: "#B0E0E6" },
    { name: "cadetblue", hex: "#5F9EA0" }, { name: "cadetblue1", hex: "#98F5FF" }, { name: "cadetblue2", hex: "#8EE5EE" },
    { name: "cadetblue3", hex: "#7AC5CD" }, { name: "cadetblue4", hex: "#53868B" }, { name: "cornflowerblue", hex: "#6495ED" },
    { name: "lightsteelblue", hex: "#B0C4DE" }, { name: "lightsteelblue1", hex: "#CAE1FF" }, { name: "lightsteelblue2", hex: "#BCD2EE" },
    { name: "lightsteelblue3", hex: "#A2B5CD" }, { name: "lightsteelblue4", hex: "#6E7B8B" },
    { name: "slateblue", hex: "#6A5ACD" }, { name: "slateblue1", hex: "#836FFF" }, { name: "slateblue2", hex: "#7A67EE" },
    { name: "slateblue3", hex: "#6959CD" }, { name: "slateblue4", hex: "#473C8B" },
    { name: "mediumslateblue", hex: "#7B68EE" }, { name: "lightslateblue", hex: "#8470FF" }, { name: "darkslateblue", hex: "#483D8B" },
    { name: "aliceblue", hex: "#F0F8FF" },
    { name: "azure", hex: "#F0FFFF" }, { name: "azure1", hex: "#F0FFFF" }, { name: "azure2", hex: "#E0EEEE" },
    { name: "azure3", hex: "#C1CDCD" }, { name: "azure4", hex: "#838B8B" },
  ]},
  { family: "Cyans & Turquoise", colors: [
    { name: "cyan", hex: "#00FFFF" }, { name: "cyan1", hex: "#00FFFF" }, { name: "cyan2", hex: "#00EEEE" },
    { name: "cyan3", hex: "#00CDCD" }, { name: "cyan4", hex: "#008B8B" }, { name: "darkcyan", hex: "#008B8B" },
    { name: "lightcyan", hex: "#E0FFFF" }, { name: "lightcyan1", hex: "#E0FFFF" }, { name: "lightcyan2", hex: "#D1EEEE" },
    { name: "lightcyan3", hex: "#B4CDCD" }, { name: "lightcyan4", hex: "#7A8B8B" },
    { name: "turquoise", hex: "#40E0D0" }, { name: "turquoise1", hex: "#00F5FF" }, { name: "turquoise2", hex: "#00E5EE" },
    { name: "turquoise3", hex: "#00C5CD" }, { name: "turquoise4", hex: "#00868B" }, { name: "darkturquoise", hex: "#00CED1" },
    { name: "mediumturquoise", hex: "#48D1CC" },
    { name: "paleturquoise", hex: "#AFEEEE" }, { name: "paleturquoise1", hex: "#BBFFFF" }, { name: "paleturquoise2", hex: "#AEEEEE" },
    { name: "paleturquoise3", hex: "#96CDCD" }, { name: "paleturquoise4", hex: "#668B8B" }, { name: "lightseagreen", hex: "#20B2AA" },
  ]},
  { family: "Purples & Violets", colors: [
    { name: "purple", hex: "#A020F0" }, { name: "purple1", hex: "#9B30FF" }, { name: "purple2", hex: "#912CEE" },
    { name: "purple3", hex: "#7D26CD" }, { name: "purple4", hex: "#551A8B" },
    { name: "darkorchid", hex: "#9932CC" }, { name: "darkorchid1", hex: "#BF3EFF" }, { name: "darkorchid2", hex: "#B23AEE" },
    { name: "darkorchid3", hex: "#9A32CD" }, { name: "darkorchid4", hex: "#68228B" },
    { name: "mediumorchid", hex: "#BA55D3" }, { name: "mediumorchid1", hex: "#E066FF" }, { name: "mediumorchid2", hex: "#D15FEE" },
    { name: "mediumorchid3", hex: "#B452CD" }, { name: "mediumorchid4", hex: "#7A378B" },
    { name: "orchid", hex: "#DA70D6" }, { name: "orchid1", hex: "#FF83FA" }, { name: "orchid2", hex: "#EE7AE9" },
    { name: "orchid3", hex: "#CD69C9" }, { name: "orchid4", hex: "#8B4789" },
    { name: "darkviolet", hex: "#9400D3" }, { name: "blueviolet", hex: "#8A2BE2" }, { name: "violet", hex: "#EE82EE" },
    { name: "darkmagenta", hex: "#8B008B" },
    { name: "magenta", hex: "#FF00FF" }, { name: "magenta1", hex: "#FF00FF" }, { name: "magenta2", hex: "#EE00EE" },
    { name: "magenta3", hex: "#CD00CD" }, { name: "magenta4", hex: "#8B008B" },
    { name: "mediumpurple", hex: "#9370DB" }, { name: "mediumpurple1", hex: "#AB82FF" }, { name: "mediumpurple2", hex: "#9F79EE" },
    { name: "mediumpurple3", hex: "#8968CD" }, { name: "mediumpurple4", hex: "#5D478B" },
    { name: "plum", hex: "#DDA0DD" }, { name: "plum1", hex: "#FFBBFF" }, { name: "plum2", hex: "#EEAEEE" },
    { name: "plum3", hex: "#CD96CD" }, { name: "plum4", hex: "#8B668B" },
    { name: "thistle", hex: "#D8BFD8" }, { name: "thistle1", hex: "#FFE1FF" }, { name: "thistle2", hex: "#EED2EE" },
    { name: "thistle3", hex: "#CDB5CD" }, { name: "thistle4", hex: "#8B7B8B" },
    { name: "lavender", hex: "#E6E6FA" },
    { name: "lavenderblush", hex: "#FFF0F5" }, { name: "lavenderblush1", hex: "#FFF0F5" }, { name: "lavenderblush2", hex: "#EEE0E5" },
    { name: "lavenderblush3", hex: "#CDC1C5" }, { name: "lavenderblush4", hex: "#8B8386" },
  ]},
  { family: "Grays, Whites & Neutrals", colors: [
    { name: "white", hex: "#FFFFFF" }, { name: "black", hex: "#000000" }, { name: "gray / grey", hex: "#BEBEBE" },
    { name: "darkgray", hex: "#A9A9A9" }, { name: "dimgray", hex: "#696969" }, { name: "lightgray", hex: "#D3D3D3" },
    { name: "gainsboro", hex: "#DCDCDC" }, { name: "whitesmoke", hex: "#F5F5F5" },
    { name: "slategray", hex: "#708090" }, { name: "slategray1", hex: "#C6E2FF" }, { name: "slategray2", hex: "#B9D3EE" },
    { name: "slategray3", hex: "#9FB6CD" }, { name: "slategray4", hex: "#6C7B8B" }, { name: "slategrey", hex: "#708090" },
    { name: "lightslategray", hex: "#778899" }, { name: "lightslategrey", hex: "#778899" },
    { name: "darkslategray", hex: "#2F4F4F" }, { name: "darkslategray1", hex: "#97FFFF" }, { name: "darkslategray2", hex: "#8DEEEE" },
    { name: "darkslategray3", hex: "#79CDCD" }, { name: "darkslategray4", hex: "#528B8B" }, { name: "darkslategrey", hex: "#2F4F4F" },
    { name: "ghostwhite", hex: "#F8F8FF" }, { name: "floralwhite", hex: "#FFFAF0" },
    { name: "ivory", hex: "#FFFFF0" }, { name: "ivory1", hex: "#FFFFF0" }, { name: "ivory2", hex: "#EEEEE0" },
    { name: "ivory3", hex: "#CDCDC1" }, { name: "ivory4", hex: "#8B8B83" },
    { name: "snow", hex: "#FFFAFA" }, { name: "snow1", hex: "#FFFAFA" }, { name: "snow2", hex: "#EEE9E9" },
    { name: "snow3", hex: "#CDC9C9" }, { name: "snow4", hex: "#8B8989" },
    { name: "linen", hex: "#FAF0E6" }, { name: "oldlace", hex: "#FDF5E6" }, { name: "beige", hex: "#F5F5DC" },
    { name: "seashell", hex: "#FFF5EE" }, { name: "seashell1", hex: "#FFF5EE" }, { name: "seashell2", hex: "#EEE5DE" },
    { name: "seashell3", hex: "#CDC5BF" }, { name: "seashell4", hex: "#8B8682" },
    { name: "mintcream", hex: "#F5FFFA" }, { name: "blanchedalmond", hex: "#FFEBCD" },
  ]},
];

const COLOR_NOTE = "This covers essentially every named base R color, including numbered shade families (steelblue1–steelblue4, red1–red4, etc). Not separately listed: the British \"grey\" spelling exists as an identical alias for every \"gray\" name (already shown once above), and R also has a gray0–gray100 grayscale ramp, generated below. Run colors() in R to see the raw list of 657 names.";

// gray0-gray100: R computes these as round(255 * n / 100) for each channel, n = 0..100
const GRAY_RAMP = Array.from({ length: 101 }, (_, n) => {
  const v = Math.round((255 * n) / 100);
  const hex = "#" + [v, v, v].map((c) => c.toString(16).padStart(2, "0").toUpperCase()).join("");
  return { name: `gray${n} / grey${n}`, hex };
});

const PALETTES = [
  {
    pkg: "viridis", fn: "viridis(n) / scale_color_viridis_c() / scale_fill_viridis_d()",
    desc: "Perceptually uniform, colorblind-friendly palettes. Great default for both continuous and discrete data.",
    example: 'ggplot(df, aes(x, y, color = value)) + geom_point() + scale_color_viridis_c()',
    swatch: ["#440154", "#3b528b", "#21908c", "#5dc963", "#fde725"],
    tags: ["palette","colorblind","continuous","viridis"],
  },
  {
    pkg: "viridis", fn: 'option = "magma" / "plasma" / "cividis"',
    desc: "Alternate viridis-family palettes; cividis is optimized for colorblind and grayscale printing.",
    example: 'scale_fill_viridis_c(option = "magma")',
    swatch: ["#000004", "#51127c", "#b73779", "#fc8961", "#fcfdbf"],
    tags: ["palette","viridis","magma","plasma"],
  },
  {
    pkg: "RColorBrewer", fn: 'brewer.pal(n, "Blues") / scale_fill_brewer(palette = "Blues")',
    desc: "Sequential palette — use for ordered/low-to-high numeric data.",
    example: 'scale_fill_brewer(palette = "Blues")',
    swatch: ["#eff3ff", "#bdd7e7", "#6baed6", "#3182bd", "#08519c"],
    tags: ["palette","brewer","sequential"],
  },
  {
    pkg: "RColorBrewer", fn: 'brewer.pal(n, "RdBu") / scale_fill_brewer(palette = "RdBu")',
    desc: "Diverging palette — use when data has a meaningful midpoint (e.g. above/below zero).",
    example: 'scale_fill_distiller(palette = "RdBu")',
    swatch: ["#ca0020", "#f4a582", "#f7f7f7", "#92c5de", "#0571b0"],
    tags: ["palette","brewer","diverging"],
  },
  {
    pkg: "RColorBrewer", fn: 'brewer.pal(n, "Set2") / scale_fill_brewer(palette = "Set2")',
    desc: "Qualitative palette — use for unordered categories, not numeric ranges.",
    example: 'scale_fill_brewer(palette = "Set2")',
    swatch: ["#66c2a5", "#fc8d62", "#8da0cb", "#e78ac3", "#a6d854"],
    tags: ["palette","brewer","qualitative","categorical"],
  },
  {
    pkg: "scales", fn: "hue_pal()(n)",
    desc: "ggplot2's own default evenly-spaced hue palette — what you get with no scale_* call at all.",
    example: "scales::hue_pal()(4)",
    swatch: ["#F8766D", "#7CAE00", "#00BFC4", "#C77CFF"],
    tags: ["palette","default","ggplot"],
  },
  {
    pkg: "grace's site palette", fn: "blue / purple accent palette",
    desc: "The blue-to-purple gradient used across this site and grace-portfolio — handy to reuse for consistent plots.",
    example: 'scale_fill_manual(values = c("#a8d4ee", "#8a72b8"))',
    swatch: ["#dbeefb", "#a8d4ee", "#5b8cb8", "#cdbcec", "#8a72b8"],
    tags: ["palette","custom","personal"],
  },
];

// Representative colors for base Shiny (no theme) and every shinythemes
// theme, so you can see the vibe of each at a glance. bg = page background,
// primary = navbar/button color, accent = secondary highlight color.
// font/fontLabel come from each theme's actual Bootswatch _variables.scss
// (headings-font-family, or font-family-sans-serif where headings inherit).
const SHINY_THEMES = [
  { name: "Default (no theme)", code: "fluidPage(...)  # Bootstrap default, no shinytheme()", bg: "#f5f5f5", primary: "#337ab7", accent: "#5bc0de", font: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif", fontLabel: "System default" },
  { name: "cerulean",  code: 'shinytheme("cerulean")',  bg: "#ffffff", primary: "#2fa4e7", accent: "#033c73", font: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif", fontLabel: "System default" },
  { name: "cosmo",     code: 'shinytheme("cosmo")',     bg: "#ffffff", primary: "#2780e3", accent: "#373a3c", font: "'Source Sans Pro', sans-serif", fontLabel: "Source Sans Pro" },
  { name: "cyborg",    code: 'shinytheme("cyborg")',    bg: "#060606", primary: "#2a9fd6", accent: "#adafae", font: "Roboto, sans-serif", fontLabel: "Roboto" },
  { name: "darkly",    code: 'shinytheme("darkly")',    bg: "#222222", primary: "#375a7d", accent: "#00bc8c", font: "Lato, sans-serif", fontLabel: "Lato" },
  { name: "flatly",    code: 'shinytheme("flatly")',    bg: "#ffffff", primary: "#2c3e50", accent: "#18bc9c", font: "Lato, sans-serif", fontLabel: "Lato" },
  { name: "journal",   code: 'shinytheme("journal")',   bg: "#ffffff", primary: "#eb6864", accent: "#22b24c", font: "'News Cycle', sans-serif", fontLabel: "News Cycle" },
  { name: "lumen",     code: 'shinytheme("lumen")',     bg: "#ffffff", primary: "#158cba", accent: "#f0ad4e", font: "'Source Sans Pro', sans-serif", fontLabel: "Source Sans Pro" },
  { name: "paper",     code: 'shinytheme("paper")',     bg: "#ffffff", primary: "#2196f3", accent: "#f5f5f5", font: "Roboto, sans-serif", fontLabel: "Roboto" },
  { name: "readable",  code: 'shinytheme("readable")',  bg: "#ffffff", primary: "#4582ec", accent: "#212529", font: "Raleway, sans-serif", fontLabel: "Raleway (body text is Georgia)" },
  { name: "sandstone", code: 'shinytheme("sandstone")', bg: "#f8f5f0", primary: "#325d88", accent: "#8e8c84", font: "Roboto, sans-serif", fontLabel: "Roboto" },
  { name: "simplex",   code: 'shinytheme("simplex")',   bg: "#ffffff", primary: "#d9230f", accent: "#0f6cbf", font: "'Open Sans', sans-serif", fontLabel: "Open Sans" },
  { name: "slate",     code: 'shinytheme("slate")',     bg: "#272b30", primary: "#7a8288", accent: "#3a3f44", font: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif", fontLabel: "System default" },
  { name: "spacelab",  code: 'shinytheme("spacelab")',  bg: "#ffffff", primary: "#446e9b", accent: "#3cb521", font: "'Open Sans', sans-serif", fontLabel: "Open Sans" },
  { name: "superhero", code: 'shinytheme("superhero")', bg: "#2b3e50", primary: "#df691a", accent: "#4e5d6c", font: "Lato, sans-serif", fontLabel: "Lato" },
  { name: "united",    code: 'shinytheme("united")',    bg: "#ffffff", primary: "#772953", accent: "#dd4814", font: "Ubuntu, sans-serif", fontLabel: "Ubuntu" },
  { name: "yeti",      code: 'shinytheme("yeti")',      bg: "#ffffff", primary: "#008cba", accent: "#adafae", font: "'Open Sans', sans-serif", fontLabel: "Open Sans" },
];

const SHINY_THEME_NOTE = "Swatches are approximate representative colors for each theme's background/navbar/accent, and each theme's name is set in its actual heading font (pulled from Bootswatch's own _variables.scss) — themes without a custom font just use the system default. For a pixel-accurate live preview, run shinythemes::themeSelector() inside an app.";

// bslib supports Bootstrap 4/5 versions of every theme name above (same
// visual family, slightly refreshed) plus these Bootstrap 4/5-only themes.
const BSLIB_THEMES = [
  { name: "minty",   code: 'bs_theme(bootswatch = "minty")',   bg: "#ffffff", primary: "#78c2ad", accent: "#ffce67", font: "Montserrat, sans-serif", fontLabel: "Montserrat" },
  { name: "litera",  code: 'bs_theme(bootswatch = "litera")',  bg: "#ffffff", primary: "#4582ec", accent: "#02b875", font: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif", fontLabel: "System default" },
  { name: "lux",     code: 'bs_theme(bootswatch = "lux")',     bg: "#ffffff", primary: "#1a1a1a", accent: "#6f42c1", font: "'Nunito Sans', sans-serif", fontLabel: "Nunito Sans" },
  { name: "materia", code: 'bs_theme(bootswatch = "materia")', bg: "#fafafa", primary: "#2196f3", accent: "#ff4081", font: "Roboto, sans-serif", fontLabel: "Roboto" },
  { name: "morph",   code: 'bs_theme(bootswatch = "morph")',   bg: "#eef2f7", primary: "#7952b3", accent: "#3a3f44", font: "Nunito, sans-serif", fontLabel: "Nunito" },
  { name: "pulse",   code: 'bs_theme(bootswatch = "pulse")',   bg: "#ffffff", primary: "#593196", accent: "#e36209", font: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif", fontLabel: "System default" },
  { name: "quartz",  code: 'bs_theme(bootswatch = "quartz")',  bg: "#ffffff", primary: "#a57dff", accent: "#12d6bf", font: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif", fontLabel: "System default" },
  { name: "sketchy", code: 'bs_theme(bootswatch = "sketchy")', bg: "#ffffff", primary: "#333333", accent: "#e3ac6c", font: "'Cabin Sketch', cursive", fontLabel: "Cabin Sketch (body is Neucha)" },
  { name: "solar",   code: 'bs_theme(bootswatch = "solar")',   bg: "#002b36", primary: "#b58900", accent: "#268bd2", font: "'Source Sans Pro', sans-serif", fontLabel: "Source Sans Pro" },
  { name: "vapor",   code: 'bs_theme(bootswatch = "vapor")',   bg: "#1b1425", primary: "#ff71ce", accent: "#01cdfe", font: "Lato, sans-serif", fontLabel: "Lato" },
  { name: "zephyr",  code: 'bs_theme(bootswatch = "zephyr")',  bg: "#ffffff", primary: "#337ab7", accent: "#f0ad4e", font: "Inter, sans-serif", fontLabel: "Inter" },
];

const BSLIB_THEME_NOTE = "bslib also includes Bootstrap 4/5 versions of every theme shown above (cerulean, cosmo, cyborg, darkly, flatly, journal, lumen, sandstone, simplex, slate, spacelab, superhero, united, yeti) in the same visual family, plus these themes unique to bslib. Swatches are approximate — run bslib::bs_theme_preview() for an exact live look.";

// ggplot2's nine built-in complete themes. panelBg = plot panel background,
// gridColor = major gridline color (null = no gridlines), border/borderColor
// = full panel border, axisLines = keep just x/y axis lines (theme_classic).
const GGPLOT_THEMES = [
  { name: "theme_gray() (default)", code: "ggplot(...) + theme_gray()", desc: "ggplot2's default: grey panel with white gridlines — applied automatically if you don't add a theme.", panelBg: "#EBEBEB", gridColor: "#FFFFFF" },
  { name: "theme_bw()",       code: "ggplot(...) + theme_bw()",       desc: "White panel, grey gridlines, full border — the classic black-and-white look.", panelBg: "#FFFFFF", gridColor: "#EBEBEB", border: true, borderColor: "#333333" },
  { name: "theme_linedraw()", code: "ggplot(...) + theme_linedraw()", desc: "Crisp black lines on white for high-contrast, print-ready plots.", panelBg: "#FFFFFF", gridColor: "#000000", border: true, borderColor: "#000000" },
  { name: "theme_light()",    code: "ggplot(...) + theme_light()",    desc: "Light grey gridlines and a soft grey border — lighter than theme_bw().", panelBg: "#FFFFFF", gridColor: "#DEDEDE", border: true, borderColor: "#B3B3B3" },
  { name: "theme_dark()",     code: "ggplot(...) + theme_dark()",     desc: "Dark grey panel that makes bright data colors pop — not a full dark mode (background stays white).", panelBg: "#7F7F7F", gridColor: "#6B6B6B" },
  { name: "theme_minimal()",  code: "ggplot(...) + theme_minimal()",  desc: "No panel background or border, just faint gridlines — clean and modern, the most commonly used alternative to the default.", panelBg: "#FFFFFF", gridColor: "#EBEBEB" },
  { name: "theme_classic()",  code: "ggplot(...) + theme_classic()",  desc: "White background, no gridlines, but keeps x/y axis lines — the classic base-R plot() look.", panelBg: "#FFFFFF", axisLines: true },
  { name: "theme_void()",     code: "ggplot(...) + theme_void()",     desc: "Strips away everything but the data itself — no axes, gridlines, ticks, or background.", panelBg: "transparent" },
  { name: "theme_test()",     code: "ggplot(...) + theme_test()",     desc: "White background with a border but no gridlines — meant for clean statistical/publication figures.", panelBg: "#FFFFFF", border: true, borderColor: "#333333" },
];

const GGPLOT_THEME_NOTE = "These are ggplot2's built-in complete themes (theme_*()), which control the plot's chrome — panel background, gridlines, and borders — not data colors. Add one with + theme_minimal() etc. after your geoms; combine with a scale_color_*()/scale_fill_*() from the palettes above for full control.";
