/* ============================================================
   RStudio Cheat Sheet — content data
   Add new entries here any time; the site re-renders automatically.
   Each entry: { fn, desc, example, tags }
   ============================================================ */

const CATEGORIES = [
  { id: "base",       name: "Base R",     blurb: "Core language: vectors, control flow, apply family, I/O." },
  { id: "dplyr",      name: "dplyr",      blurb: "Data wrangling verbs: filter, select, mutate, join, summarise." },
  { id: "tidyr",      name: "tidyr",      blurb: "Reshaping data: long/wide, splitting, filling, nesting." },
  { id: "ggplot2",    name: "ggplot2",    blurb: "Grammar-of-graphics plotting." },
  { id: "stringr",    name: "stringr",    blurb: "Consistent, readable string manipulation." },
  { id: "lubridate",  name: "lubridate",  blurb: "Parsing and arithmetic on dates and times." },
  { id: "rvest",      name: "rvest",      blurb: "Web scraping: pull data out of HTML pages." },
  { id: "scales",     name: "scales",     blurb: "Axis/label formatting and palette helpers." },
  { id: "tidyverse",  name: "Tidyverse misc", blurb: "purrr, tibble, readr, and other tidyverse odds and ends." },
  { id: "forcats",    name: "forcats",    blurb: "Reordering, collapsing, and cleaning up factor levels." },
  { id: "stats",      name: "Stats & modeling", blurb: "Base R modeling and hypothesis-testing functions." },
  { id: "broom",      name: "broom",      blurb: "Turn model objects into tidy data frames." },
  { id: "janitor",    name: "janitor",    blurb: "Fast data-cleaning helpers: names, duplicates, tables." },
  { id: "tidytext",   name: "tidytext",   blurb: "Tokenizing, tidying, and analyzing text data." },
  { id: "knitr",      name: "knitr",      blurb: "Rendering reports and formatting output tables." },
  { id: "plotly",     name: "plotly",     blurb: "Interactive, zoomable, hoverable charts." },
];

const ENTRIES = [
  // ---------------- Base R ----------------
  { cat: "base", fn: "c(...)", desc: "Combine values into a vector.", example: 'x <- c(1, 2, 3)', tags: ["vector","create","combine"] },
  { cat: "base", fn: "seq(from, to, by)", desc: "Generate a regular sequence of numbers.", example: "seq(1, 10, by = 2)", tags: ["sequence","range"] },
  { cat: "base", fn: "rep(x, times)", desc: "Repeat a value or vector.", example: 'rep("a", times = 3)', tags: ["repeat"] },
  { cat: "base", fn: "length(x)", desc: "Number of elements in a vector/list.", example: "length(x)", tags: ["size","count"] },
  { cat: "base", fn: "str(x)", desc: "Compactly display the internal structure of an object.", example: "str(mtcars)", tags: ["inspect","structure","explore"] },
  { cat: "base", fn: "summary(x)", desc: "Quick summary stats (min/max/mean/quartiles) for a vector or data frame.", example: "summary(mtcars$mpg)", tags: ["stats","explore","describe"] },
  { cat: "base", fn: "head(x, n) / tail(x, n)", desc: "First or last n rows/elements.", example: "head(mtcars, 5)", tags: ["preview","rows"] },
  { cat: "base", fn: "paste(..., sep) / paste0(...)", desc: "Concatenate strings. paste0 has sep = \"\" by default.", example: 'paste0("row_", 1:3)', tags: ["string","concatenate","combine"] },
  { cat: "base", fn: "sprintf(fmt, ...)", desc: "Format strings/numbers C-style (like %.2f, %d, %s).", example: 'sprintf("%.2f%%", 12.345)', tags: ["string","format","printf"] },
  { cat: "base", fn: "ifelse(test, yes, no)", desc: "Vectorized if/else.", example: 'ifelse(x > 0, "pos", "neg")', tags: ["conditional","logic"] },
  { cat: "base", fn: "if (cond) { } else { }", desc: "Standard (non-vectorized) conditional control flow.", example: 'if (x > 0) print("pos") else print("neg")', tags: ["conditional","logic","control flow"] },
  { cat: "base", fn: "for (i in seq_along(x)) { }", desc: "For-loop iterating over indices/elements.", example: "for (i in 1:5) print(i)", tags: ["loop","iterate","control flow"] },
  { cat: "base", fn: "while (cond) { }", desc: "Loop that runs while a condition stays TRUE.", example: "while (x < 10) x <- x + 1", tags: ["loop","control flow"] },
  { cat: "base", fn: "function(args) { }", desc: "Define a custom function.", example: "sq <- function(x) x^2", tags: ["function","define","custom"] },
  { cat: "base", fn: "sapply(x, FUN)", desc: "Apply a function over a vector/list, simplify result to vector/matrix.", example: "sapply(1:5, sqrt)", tags: ["apply","loop","functional"] },
  { cat: "base", fn: "lapply(x, FUN)", desc: "Apply a function over a list, always returns a list.", example: "lapply(1:3, function(i) i * 2)", tags: ["apply","loop","functional"] },
  { cat: "base", fn: "vapply(x, FUN, FUN.VALUE)", desc: "Like sapply but with a specified, checked output type — safer in scripts.", example: "vapply(1:5, sqrt, numeric(1))", tags: ["apply","loop","functional"] },
  { cat: "base", fn: "mapply(FUN, ...)", desc: "Apply a function over multiple vectors in parallel.", example: "mapply(function(a,b) a+b, 1:3, 4:6)", tags: ["apply","loop","functional"] },
  { cat: "base", fn: "apply(X, MARGIN, FUN)", desc: "Apply a function over rows (1) or columns (2) of a matrix/data frame.", example: "apply(mtcars, 2, mean)", tags: ["apply","loop","functional","matrix"] },
  { cat: "base", fn: "which(x)", desc: "Indices where a logical vector is TRUE.", example: "which(x > 5)", tags: ["index","filter","logic"] },
  { cat: "base", fn: "which.max(x) / which.min(x)", desc: "Index of the maximum/minimum value.", example: "which.max(mtcars$mpg)", tags: ["index","max","min"] },
  { cat: "base", fn: "is.na(x)", desc: "Logical vector flagging missing values.", example: "sum(is.na(df$col))", tags: ["missing","na","logic"] },
  { cat: "base", fn: "na.omit(x)", desc: "Remove rows/elements containing NA.", example: "na.omit(df)", tags: ["missing","na","clean"] },
  { cat: "base", fn: "sum(x, na.rm = TRUE)", desc: "Sum of a vector, optionally ignoring NAs.", example: "sum(x, na.rm = TRUE)", tags: ["stats","math","aggregate"] },
  { cat: "base", fn: "mean(x, na.rm = TRUE)", desc: "Arithmetic mean.", example: "mean(mtcars$mpg)", tags: ["stats","average","aggregate"] },
  { cat: "base", fn: "median(x)", desc: "Median value.", example: "median(mtcars$mpg)", tags: ["stats","average"] },
  { cat: "base", fn: "sd(x) / var(x)", desc: "Standard deviation / variance.", example: "sd(mtcars$mpg)", tags: ["stats","spread"] },
  { cat: "base", fn: "range(x)", desc: "Minimum and maximum as a length-2 vector.", example: "range(mtcars$mpg)", tags: ["stats","min","max"] },
  { cat: "base", fn: "sort(x) / order(x)", desc: "sort() reorders values; order() returns the sorting indices (great for reordering a whole data frame).", example: "df[order(df$mpg), ]", tags: ["sort","arrange","rank"] },
  { cat: "base", fn: "rev(x)", desc: "Reverse the order of elements.", example: "rev(1:5)", tags: ["reverse","order"] },
  { cat: "base", fn: "unique(x)", desc: "Unique values, duplicates removed.", example: "unique(df$category)", tags: ["distinct","duplicates"] },
  { cat: "base", fn: "duplicated(x)", desc: "Logical vector flagging which elements are duplicates.", example: "df[!duplicated(df$id), ]", tags: ["distinct","duplicates"] },
  { cat: "base", fn: "table(x)", desc: "Frequency count / contingency table.", example: "table(df$category)", tags: ["count","frequency","tabulate"] },
  { cat: "base", fn: "merge(x, y, by)", desc: "Base-R join of two data frames.", example: 'merge(df1, df2, by = "id")', tags: ["join","merge","combine"] },
  { cat: "base", fn: "rbind(...) / cbind(...)", desc: "Bind rows or columns together.", example: "rbind(df1, df2)", tags: ["combine","bind","rows","columns"] },
  { cat: "base", fn: "nrow(x) / ncol(x) / dim(x)", desc: "Number of rows, columns, or both.", example: "dim(mtcars)", tags: ["size","dimensions"] },
  { cat: "base", fn: "names(x) / colnames(x) / rownames(x)", desc: "Get or set the names of a list/data frame's columns or rows.", example: "colnames(df) <- c(\"a\",\"b\")", tags: ["names","columns","labels"] },
  { cat: "base", fn: "df[rows, cols] / df$col / df[[\"col\"]]", desc: "Core indexing: bracket subsetting, $ for a named column, [[ ]] for extraction.", example: 'df[1:5, "mpg"]', tags: ["index","subset","select"] },
  { cat: "base", fn: "class(x) / typeof(x)", desc: "Object's class (S3/S4 type) vs. its underlying storage type.", example: "class(df$date)", tags: ["type","inspect"] },
  { cat: "base", fn: "as.numeric(x) / as.character(x) / as.factor(x)", desc: "Coerce a vector to another type.", example: "as.numeric(df$year)", tags: ["convert","coerce","type"] },
  { cat: "base", fn: "round(x, digits) / floor(x) / ceiling(x)", desc: "Rounding helpers.", example: "round(3.14159, 2)", tags: ["math","round","number"] },
  { cat: "base", fn: "x %in% table", desc: "Test membership: is each element of x found in table?", example: 'df$grp %in% c("A","B")', tags: ["membership","filter","logic"] },
  { cat: "base", fn: "match(x, table)", desc: "Position of first match of each x in table (NA if none).", example: 'match("b", c("a","b","c"))', tags: ["lookup","index"] },
  { cat: "base", fn: "grepl(pattern, x) / grep(pattern, x)", desc: "Base-R regex matching: grepl returns logical, grep returns matching indices/values.", example: 'grepl("^A", df$name)', tags: ["regex","pattern","search","string"] },
  { cat: "base", fn: "sub(pattern, repl, x) / gsub(pattern, repl, x)", desc: "Replace first (sub) or all (gsub) regex matches.", example: 'gsub("-", "_", x)', tags: ["regex","replace","string"] },
  { cat: "base", fn: "read.csv(file) / write.csv(x, file)", desc: "Base-R CSV import/export.", example: 'df <- read.csv("data.csv")', tags: ["import","export","csv","io"] },
  { cat: "base", fn: "getwd() / setwd(dir)", desc: "Get or set the working directory.", example: 'setwd("~/projects")', tags: ["directory","file","io"] },
  { cat: "base", fn: "library(pkg) / install.packages(\"pkg\")", desc: "Load an installed package / install a new one from CRAN.", example: "library(tidyverse)", tags: ["package","install","load"] },
  { cat: "base", fn: "tryCatch(expr, error = function(e) ...)", desc: "Catch and handle errors/warnings gracefully.", example: 'tryCatch(1/"a", error = function(e) NA)', tags: ["error","exception","debug"] },
  { cat: "base", fn: "Reduce(f, x) / Map(f, x, y) / Filter(f, x)", desc: "Functional-programming helpers: fold, parallel-map, and predicate-filter.", example: "Reduce(`+`, 1:5)", tags: ["functional","fold","map","filter"] },
  { cat: "base", fn: "do.call(fun, args)", desc: "Call a function with arguments supplied as a list.", example: 'do.call(rbind, list_of_dfs)', tags: ["functional","call"] },
  { cat: "base", fn: "set.seed(n)", desc: "Fix the random number generator seed for reproducibility.", example: "set.seed(42)", tags: ["random","reproducible","seed"] },
  { cat: "base", fn: "sample(x, size)", desc: "Draw a random sample from a vector.", example: "sample(1:10, 3)", tags: ["random","sample"] },
  { cat: "base", fn: "rnorm(n, mean, sd) / runif(n, min, max)", desc: "Generate random draws from normal / uniform distributions.", example: "rnorm(100, mean = 0, sd = 1)", tags: ["random","distribution","simulate"] },
  { cat: "base", fn: "factor(x, levels)", desc: "Create a categorical variable with defined levels/order.", example: 'factor(df$grade, levels = c("Low","Mid","High"))', tags: ["categorical","factor","levels"] },
  { cat: "base", fn: "cut(x, breaks)", desc: "Bucket a continuous variable into discrete intervals.", example: "cut(df$age, breaks = c(0,18,65,100))", tags: ["bin","bucket","discretize"] },
  { cat: "base", fn: "format(x, ...)", desc: "Format numbers/dates as strings for display.", example: 'format(Sys.Date(), "%B %d, %Y")', tags: ["format","display","string"] },
  { cat: "base", fn: "Sys.Date() / Sys.time()", desc: "Current date / current date-time.", example: "Sys.Date()", tags: ["date","time","now"] },
  { cat: "base", fn: "identical(x, y) / all.equal(x, y)", desc: "Exact equality check vs. near-equality check (for floats).", example: "identical(1L, 1)", tags: ["compare","equal","test"] },
  { cat: "base", fn: "stopifnot(cond)", desc: "Throw an error if a condition is not TRUE — cheap assertions.", example: "stopifnot(nrow(df) > 0)", tags: ["assert","error","validate"] },

  // ---------------- dplyr ----------------
  { cat: "dplyr", fn: "select(.data, ...)", desc: "Keep, drop, reorder, or rename columns.", example: "select(df, name, age)", tags: ["columns","subset"] },
  { cat: "dplyr", fn: "filter(.data, ...)", desc: "Keep rows matching a logical condition.", example: "filter(df, age > 21)", tags: ["rows","subset","where"] },
  { cat: "dplyr", fn: "mutate(.data, ...)", desc: "Add new columns or modify existing ones.", example: "mutate(df, bmi = weight / height^2)", tags: ["column","create","transform"] },
  { cat: "dplyr", fn: "summarise(.data, ...) / summarize(...)", desc: "Collapse rows to one (or one per group) summary row.", example: "summarise(df, avg = mean(mpg))", tags: ["aggregate","summary","group"] },
  { cat: "dplyr", fn: "group_by(.data, ...)", desc: "Group rows for per-group mutate/summarise operations.", example: "df %>% group_by(cyl) %>% summarise(avg = mean(mpg))", tags: ["group","aggregate"] },
  { cat: "dplyr", fn: "ungroup(.data)", desc: "Remove grouping so later steps operate on the whole data frame.", example: "df %>% group_by(cyl) %>% mutate(n = n()) %>% ungroup()", tags: ["group"] },
  { cat: "dplyr", fn: "arrange(.data, ...)", desc: "Sort rows by one or more columns; wrap in desc() to reverse.", example: "arrange(df, desc(mpg))", tags: ["sort","order"] },
  { cat: "dplyr", fn: "rename(.data, new = old)", desc: "Rename columns.", example: "rename(df, mpg_new = mpg)", tags: ["column","rename"] },
  { cat: "dplyr", fn: "distinct(.data, ...)", desc: "Keep only unique rows (optionally by specific columns).", example: "distinct(df, category)", tags: ["unique","duplicates"] },
  { cat: "dplyr", fn: "slice(.data, n) / slice_head() / slice_max()", desc: "Select rows by position, from the top, or by max value of a column.", example: "slice_max(df, mpg, n = 5)", tags: ["rows","subset","top"] },
  { cat: "dplyr", fn: "count(.data, ...)", desc: "Count rows per group — shortcut for group_by() + summarise(n = n()).", example: "count(df, category)", tags: ["count","frequency","tally"] },
  { cat: "dplyr", fn: "pull(.data, var)", desc: "Extract a single column as a vector (not a data frame).", example: "pull(df, mpg)", tags: ["extract","column","vector"] },
  { cat: "dplyr", fn: "across(cols, .fns)", desc: "Apply the same function(s) across multiple columns inside mutate/summarise.", example: 'df %>% summarise(across(where(is.numeric), mean))', tags: ["multiple columns","apply","transform"] },
  { cat: "dplyr", fn: "case_when(...)", desc: "Vectorized multi-branch if/else — cleaner than nested ifelse().", example: 'mutate(df, grp = case_when(age < 18 ~ "minor", TRUE ~ "adult"))', tags: ["conditional","logic","recode"] },
  { cat: "dplyr", fn: "if_else(condition, true, false)", desc: "Stricter, type-safe version of base ifelse().", example: 'if_else(x > 0, "pos", "neg")', tags: ["conditional","logic"] },
  { cat: "dplyr", fn: "bind_rows(...) / bind_cols(...)", desc: "Stack data frames by row or column (tidyverse version of rbind/cbind).", example: "bind_rows(df1, df2)", tags: ["combine","stack","append"] },
  { cat: "dplyr", fn: "left_join / right_join / inner_join / full_join(x, y, by)", desc: "SQL-style joins between two data frames.", example: 'left_join(df1, df2, by = "id")', tags: ["join","merge","combine"] },
  { cat: "dplyr", fn: "anti_join(x, y, by) / semi_join(x, y, by)", desc: "Filter x to rows without (anti) or with (semi) a match in y — keeps only x's columns.", example: 'anti_join(orders, cancelled, by = "order_id")', tags: ["join","filter"] },
  { cat: "dplyr", fn: "relocate(.data, ...)", desc: "Move columns to a new position.", example: "relocate(df, id, .before = everything())", tags: ["column","reorder"] },
  { cat: "dplyr", fn: "lag(x) / lead(x)", desc: "Access the previous/next value in a vector — useful for time series comparisons.", example: "mutate(df, change = value - lag(value))", tags: ["time series","shift","previous"] },
  { cat: "dplyr", fn: "n() / n_distinct(x)", desc: "Count of rows in current group / count of distinct values.", example: "summarise(df, n = n())", tags: ["count","group"] },
  { cat: "dplyr", fn: "between(x, left, right)", desc: "Shortcut for x >= left & x <= right.", example: "filter(df, between(age, 18, 65))", tags: ["filter","range"] },
  { cat: "dplyr", fn: "coalesce(...)", desc: "Return the first non-NA value at each position across vectors.", example: "coalesce(df$phone, df$backup_phone)", tags: ["missing","na","fallback"] },
  { cat: "dplyr", fn: "rowwise(.data)", desc: "Perform operations one row at a time (e.g. row-wise mean across columns).", example: "df %>% rowwise() %>% mutate(total = sum(c_across(a:c)))", tags: ["row","apply"] },
  { cat: "dplyr", fn: "sample_n(.data, size) / sample_frac(.data, size)", desc: "Randomly sample rows or a fraction of rows.", example: "sample_n(df, 10)", tags: ["random","sample"] },

  // ---------------- tidyr ----------------
  { cat: "tidyr", fn: "pivot_longer(data, cols, names_to, values_to)", desc: "Reshape wide columns into long name/value pairs.", example: 'pivot_longer(df, cols = jan:dec, names_to = "month", values_to = "sales")', tags: ["reshape","wide to long","melt"] },
  { cat: "tidyr", fn: "pivot_wider(data, names_from, values_from)", desc: "Reshape long data into wide columns.", example: 'pivot_wider(df, names_from = month, values_from = sales)', tags: ["reshape","long to wide","cast"] },
  { cat: "tidyr", fn: "separate(data, col, into, sep)", desc: "Split one column into several using a separator.", example: 'separate(df, name, into = c("first","last"), sep = " ")', tags: ["split","column","string"] },
  { cat: "tidyr", fn: "separate_rows(data, col, sep)", desc: "Split a delimited string column into multiple rows.", example: 'separate_rows(df, tags, sep = ",")', tags: ["split","rows","string"] },
  { cat: "tidyr", fn: "unite(data, col, ..., sep)", desc: "Combine several columns into one (opposite of separate).", example: 'unite(df, full_name, first, last, sep = " ")', tags: ["combine","column","string"] },
  { cat: "tidyr", fn: "drop_na(data, ...)", desc: "Drop rows containing NA in any/specified columns.", example: "drop_na(df, age)", tags: ["missing","na","clean"] },
  { cat: "tidyr", fn: "replace_na(data, replace)", desc: "Replace NAs with a specified value.", example: 'replace_na(df, list(age = 0))', tags: ["missing","na","fill"] },
  { cat: "tidyr", fn: "fill(data, ..., .direction)", desc: "Fill NAs by carrying the last (or next) non-missing value forward/backward.", example: "fill(df, category, .direction = \"down\")", tags: ["missing","na","fill","forward fill"] },
  { cat: "tidyr", fn: "nest(data, ...) / unnest(data, col)", desc: "Collapse groups into list-columns of tibbles, or expand them back out.", example: "df %>% group_by(id) %>% nest()", tags: ["nested","list column"] },
  { cat: "tidyr", fn: "expand(data, ...) / complete(data, ...)", desc: "Create all combinations of variables; complete() also fills in missing combos with NA.", example: "complete(df, year, category)", tags: ["combinations","missing rows"] },
  { cat: "tidyr", fn: "crossing(...)", desc: "Generate a data frame from every combination of the given vectors.", example: 'crossing(size = c("S","M","L"), color = c("red","blue"))', tags: ["combinations","grid"] },
  { cat: "tidyr", fn: "uncount(data, weights)", desc: "Duplicate rows according to a weighting/count column (opposite of count()).", example: "uncount(df, n)", tags: ["expand","repeat","rows"] },

  // ---------------- ggplot2 ----------------
  { cat: "ggplot2", fn: "ggplot(data, aes(x, y))", desc: "Initialize a plot and map data columns to visual aesthetics.", example: 'ggplot(mtcars, aes(x = wt, y = mpg))', tags: ["initialize","aesthetics","setup"] },
  { cat: "ggplot2", fn: "geom_point()", desc: "Scatterplot layer.", example: "ggplot(mtcars, aes(wt, mpg)) + geom_point()", tags: ["scatter","points"] },
  { cat: "ggplot2", fn: "geom_line()", desc: "Line layer, typically for time series or ordered data.", example: "ggplot(df, aes(date, value)) + geom_line()", tags: ["line","time series"] },
  { cat: "ggplot2", fn: "geom_bar()", desc: "Bar chart of counts (computes counts automatically from raw data).", example: "ggplot(df, aes(category)) + geom_bar()", tags: ["bar","count","categorical"] },
  { cat: "ggplot2", fn: "geom_col()", desc: "Bar chart where bar heights come directly from a column of values.", example: "ggplot(df, aes(category, total)) + geom_col()", tags: ["bar","column"] },
  { cat: "ggplot2", fn: "geom_histogram(bins)", desc: "Histogram of a continuous variable's distribution.", example: "ggplot(mtcars, aes(mpg)) + geom_histogram(bins = 20)", tags: ["histogram","distribution"] },
  { cat: "ggplot2", fn: "geom_boxplot()", desc: "Boxplot showing median/quartiles/outliers, usually by group.", example: "ggplot(mtcars, aes(factor(cyl), mpg)) + geom_boxplot()", tags: ["boxplot","distribution","group"] },
  { cat: "ggplot2", fn: "geom_violin()", desc: "Violin plot — density shape mirrored, good alternative to boxplot.", example: "ggplot(mtcars, aes(factor(cyl), mpg)) + geom_violin()", tags: ["distribution","density","group"] },
  { cat: "ggplot2", fn: "geom_smooth(method)", desc: "Add a fitted trend line (e.g. \"lm\" or \"loess\") with confidence ribbon.", example: 'geom_smooth(method = "lm")', tags: ["trend","regression","fit"] },
  { cat: "ggplot2", fn: "geom_density()", desc: "Smoothed kernel density curve.", example: "ggplot(mtcars, aes(mpg)) + geom_density()", tags: ["density","distribution"] },
  { cat: "ggplot2", fn: "geom_area()", desc: "Filled area under a line, often stacked by group.", example: "ggplot(df, aes(date, value)) + geom_area()", tags: ["area","time series","stacked"] },
  { cat: "ggplot2", fn: "geom_tile() / geom_raster()", desc: "Heatmap-style tiles colored by a value.", example: "ggplot(df, aes(x, y, fill = value)) + geom_tile()", tags: ["heatmap","tile","grid"] },
  { cat: "ggplot2", fn: "geom_text() / geom_label()", desc: "Add text/labels at data coordinates.", example: "geom_text(aes(label = round(mpg,1)))", tags: ["labels","annotate","text"] },
  { cat: "ggplot2", fn: "geom_errorbar()", desc: "Vertical error bars, e.g. for showing standard error or CI.", example: "geom_errorbar(aes(ymin = low, ymax = high))", tags: ["error bars","uncertainty"] },
  { cat: "ggplot2", fn: "facet_wrap(~ var)", desc: "Split into a grid of small multiples by one variable.", example: "facet_wrap(~ cyl)", tags: ["facet","small multiples","panels"] },
  { cat: "ggplot2", fn: "facet_grid(rows ~ cols)", desc: "Facet by two variables laid out on a strict grid.", example: "facet_grid(gear ~ cyl)", tags: ["facet","panels","grid"] },
  { cat: "ggplot2", fn: "labs(title, x, y, fill, ...)", desc: "Set plot title, subtitle, axis labels, and legend titles.", example: 'labs(title = "MPG vs Weight", x = "Weight", y = "MPG")', tags: ["title","labels","axis"] },
  { cat: "ggplot2", fn: "theme_minimal() / theme_bw() / theme_classic()", desc: "Preset overall plot themes.", example: "p + theme_minimal()", tags: ["theme","style","appearance"] },
  { cat: "ggplot2", fn: "theme(...)", desc: "Fine-grained control of non-data plot elements (fonts, gridlines, legend position, etc).", example: 'theme(legend.position = "bottom")', tags: ["theme","customize","style"] },
  { cat: "ggplot2", fn: "scale_x_continuous() / scale_y_continuous(...)", desc: "Control axis breaks, limits, and labels for continuous scales.", example: "scale_y_continuous(labels = scales::comma)", tags: ["axis","scale","continuous"] },
  { cat: "ggplot2", fn: "scale_color_manual(values) / scale_fill_manual(values)", desc: "Manually set discrete colors/fills mapped to group levels.", example: 'scale_fill_manual(values = c("A" = "#a8d4ee", "B" = "#cdbcec"))', tags: ["color","fill","manual","palette"] },
  { cat: "ggplot2", fn: "scale_color_gradient(low, high) / scale_fill_gradient(...)", desc: "Continuous two-color gradient scale.", example: 'scale_fill_gradient(low = "white", high = "steelblue")', tags: ["color","gradient","continuous","palette"] },
  { cat: "ggplot2", fn: "coord_flip()", desc: "Swap x and y axes (e.g. horizontal bar charts).", example: "ggplot(df, aes(category, value)) + geom_col() + coord_flip()", tags: ["flip","horizontal","orientation"] },
  { cat: "ggplot2", fn: "ggsave(filename, plot, width, height, dpi)", desc: "Save the last (or specified) plot to a file.", example: 'ggsave("plot.png", width = 6, height = 4, dpi = 300)', tags: ["save","export","file"] },
  { cat: "ggplot2", fn: "position_dodge() / position_stack() / position_jitter()", desc: "Adjust how overlapping geoms are positioned (side-by-side, stacked, or jittered).", example: "geom_bar(position = \"dodge\")", tags: ["position","overlap","layout"] },
  { cat: "ggplot2", fn: "guides(color = guide_legend(...))", desc: "Customize legend appearance per aesthetic.", example: 'guides(color = guide_legend(title = "Group"))', tags: ["legend","guide"] },
  { cat: "ggplot2", fn: "element_text() / element_blank() / element_line()", desc: "Used inside theme() to style or remove specific plot elements.", example: "theme(axis.text.x = element_text(angle = 45))", tags: ["theme","style","element"] },

  // ---------------- stringr ----------------
  { cat: "stringr", fn: "str_detect(string, pattern)", desc: "Does the string contain a match for the pattern? Returns logical.", example: 'str_detect(df$name, "^A")', tags: ["regex","search","logic"] },
  { cat: "stringr", fn: "str_extract(string, pattern) / str_extract_all(...)", desc: "Extract the first (or all) matching substrings.", example: 'str_extract(text, "[0-9]+")', tags: ["regex","extract"] },
  { cat: "stringr", fn: "str_replace(string, pattern, replacement) / str_replace_all(...)", desc: "Replace the first (or all) pattern matches.", example: 'str_replace_all(x, "-", "_")', tags: ["regex","replace"] },
  { cat: "stringr", fn: "str_split(string, pattern)", desc: "Split a string into pieces by a separator/pattern.", example: 'str_split(x, ",")', tags: ["split","tokenize"] },
  { cat: "stringr", fn: "str_length(string)", desc: "Number of characters in a string.", example: "str_length(df$name)", tags: ["length","size","count"] },
  { cat: "stringr", fn: "str_sub(string, start, end)", desc: "Extract a substring by position.", example: 'str_sub(x, 1, 3)', tags: ["substring","extract","position"] },
  { cat: "stringr", fn: "str_trim(string) / str_squish(string)", desc: "Remove leading/trailing whitespace; squish also collapses internal whitespace.", example: "str_squish(\"  a   b \")", tags: ["whitespace","trim","clean"] },
  { cat: "stringr", fn: "str_to_upper() / str_to_lower() / str_to_title()", desc: "Change string case.", example: "str_to_title(\"grace flandreau\")", tags: ["case","upper","lower","title"] },
  { cat: "stringr", fn: "str_pad(string, width, side, pad)", desc: "Pad a string to a fixed width (e.g. leading zeros).", example: 'str_pad("7", width = 3, pad = "0")', tags: ["pad","format","width"] },
  { cat: "stringr", fn: "str_c(..., sep, collapse)", desc: "Concatenate strings (stringr's paste), with easy NA handling.", example: 'str_c("id_", 1:3)', tags: ["concatenate","combine","paste"] },
  { cat: "stringr", fn: "str_count(string, pattern)", desc: "Count how many times a pattern occurs in each string.", example: 'str_count(x, "a")', tags: ["count","regex"] },
  { cat: "stringr", fn: "str_starts(string, pattern) / str_ends(string, pattern)", desc: "Test whether strings start/end with a pattern.", example: 'str_starts(x, "https")', tags: ["prefix","suffix","logic"] },
  { cat: "stringr", fn: "str_remove(string, pattern) / str_remove_all(...)", desc: "Remove the first (or all) pattern matches — shortcut for replace with \"\".", example: 'str_remove_all(x, "[0-9]")', tags: ["remove","regex","clean"] },
  { cat: "stringr", fn: "str_glue(...)", desc: "Interpolate variables directly into a string using {braces}.", example: 'str_glue("{name} is {age} years old")', tags: ["interpolate","format","template"] },
  { cat: "stringr", fn: "str_wrap(string, width)", desc: "Wrap text to a given line width (e.g. for plot labels).", example: "str_wrap(long_text, width = 40)", tags: ["wrap","format","display"] },
  { cat: "stringr", fn: "str_dup(string, times)", desc: "Repeat and concatenate a string n times.", example: 'str_dup("ab", 3)', tags: ["repeat","duplicate"] },
  { cat: "stringr", fn: "str_order(x) / str_sort(x)", desc: "Sort or get sort order of strings (locale-aware).", example: "str_sort(df$name)", tags: ["sort","order","alphabetical"] },

  // ---------------- lubridate ----------------
  { cat: "lubridate", fn: "ymd(\"2024-01-15\") / mdy(...) / dmy(...)", desc: "Parse a date string in year-month-day / month-day-year / day-month-year order.", example: 'ymd("2024-01-15")', tags: ["parse","date","convert"] },
  { cat: "lubridate", fn: "ymd_hms(\"2024-01-15 08:30:00\")", desc: "Parse a full date-time string.", example: 'ymd_hms("2024-01-15 08:30:00")', tags: ["parse","datetime"] },
  { cat: "lubridate", fn: "today() / now()", desc: "Current date / current date-time.", example: "today()", tags: ["current","date","now"] },
  { cat: "lubridate", fn: "year(x) / month(x) / day(x)", desc: "Extract the year, month, or day component from a date.", example: "year(df$date)", tags: ["extract","component","date"] },
  { cat: "lubridate", fn: "hour(x) / minute(x) / second(x)", desc: "Extract time components from a date-time.", example: "hour(df$timestamp)", tags: ["extract","component","time"] },
  { cat: "lubridate", fn: "wday(x, label = TRUE)", desc: "Day of the week, optionally as a labeled factor (Mon, Tue, ...).", example: "wday(df$date, label = TRUE)", tags: ["weekday","day of week"] },
  { cat: "lubridate", fn: "floor_date(x, unit) / ceiling_date(x, unit) / round_date(x, unit)", desc: "Round a date-time down/up/nearest to a unit (\"week\", \"month\", etc).", example: 'floor_date(df$date, "month")', tags: ["round","bucket","aggregate"] },
  { cat: "lubridate", fn: "interval(start, end)", desc: "Create a time span between two date-times.", example: "interval(start_date, end_date)", tags: ["interval","span","duration"] },
  { cat: "lubridate", fn: "start %--% end", desc: "Shorthand operator for creating an interval.", example: "start_date %--% end_date", tags: ["interval","span"] },
  { cat: "lubridate", fn: "dseconds(x) / dminutes(x) / dhours(x) / ddays(x)", desc: "Create exact-length durations (fixed number of seconds).", example: "dhours(2)", tags: ["duration","add","subtract"] },
  { cat: "lubridate", fn: "seconds(x) / minutes(x) / hours(x) / days(x) / weeks(x) / years(x)", desc: "Create calendar-aware periods (e.g. respects month length, leap years).", example: "df$date + months(1)", tags: ["period","add","subtract"] },
  { cat: "lubridate", fn: "time_length(interval, unit)", desc: "Numeric length of an interval/duration in a given unit.", example: 'time_length(interval(start, end), "days")', tags: ["duration","length","difference"] },
  { cat: "lubridate", fn: "as_date(x)", desc: "Coerce to a Date object.", example: "as_date(\"2024-01-15\")", tags: ["convert","coerce","date"] },
  { cat: "lubridate", fn: "make_date(year, month, day)", desc: "Build a Date from separate year/month/day columns.", example: "make_date(df$yr, df$mo, df$dy)", tags: ["create","date","build"] },
  { cat: "lubridate", fn: "is.Date(x) / leap_year(x)", desc: "Check if an object is a Date / whether a year is a leap year.", example: "leap_year(2024)", tags: ["check","test","logic"] },

  // ---------------- rvest ----------------
  { cat: "rvest", fn: "read_html(url_or_string)", desc: "Fetch and parse HTML from a URL or raw string into a document you can query.", example: 'page <- read_html("https://example.com")', tags: ["scrape","fetch","html","parse"] },
  { cat: "rvest", fn: "html_element(x, css) / html_elements(x, css)", desc: "Select the first (or all) elements matching a CSS selector.", example: 'html_elements(page, ".product-title")', tags: ["select","css","query"] },
  { cat: "rvest", fn: "html_text(x) / html_text2(x)", desc: "Extract visible text from selected elements; html_text2 cleans whitespace/line breaks better.", example: "html_text2(html_elements(page, \"h1\"))", tags: ["text","extract","content"] },
  { cat: "rvest", fn: "html_attr(x, name)", desc: "Extract an HTML attribute's value (e.g. href, src).", example: 'html_attr(html_elements(page, "a"), "href")', tags: ["attribute","link","extract"] },
  { cat: "rvest", fn: "html_table(x)", desc: "Parse an HTML <table> into a data frame.", example: "html_table(html_element(page, \"table\"))", tags: ["table","parse","dataframe"] },
  { cat: "rvest", fn: "html_name(x)", desc: "Get the tag name of selected elements (e.g. \"div\", \"a\").", example: "html_name(html_elements(page, \"body *\"))", tags: ["tag","name","inspect"] },
  { cat: "rvest", fn: "html_form(x) / html_form_set(...) / session_submit(...)", desc: "Read, fill in, and submit an HTML form for interactive scraping sessions.", example: "html_form(page)", tags: ["form","submit","session"] },
  { cat: "rvest", fn: "minimal_html(html_string)", desc: "Parse a small snippet of raw HTML — handy for testing selectors.", example: 'minimal_html("<p class=\'a\'>hi</p>")', tags: ["test","parse","snippet"] },

  // ---------------- scales ----------------
  { cat: "scales", fn: "comma(x) / label_comma()", desc: "Format numbers with thousands separators, e.g. 1,234,567.", example: "scales::comma(1234567)", tags: ["format","number","label"] },
  { cat: "scales", fn: "percent(x) / label_percent()", desc: "Format a proportion (0-1) as a percentage string.", example: "scales::percent(0.256)", tags: ["format","percent","label"] },
  { cat: "scales", fn: "dollar(x) / label_dollar()", desc: "Format numbers as currency, e.g. $1,234.56.", example: "scales::dollar(1234.5)", tags: ["format","currency","money","label"] },
  { cat: "scales", fn: "scientific(x) / label_scientific()", desc: "Format numbers in scientific notation.", example: "scales::scientific(123456)", tags: ["format","scientific","number"] },
  { cat: "scales", fn: "pretty_breaks(n) / breaks_pretty(n)", desc: "Generate nicely rounded axis break points — pass to scale_*_continuous(breaks = ...).", example: "scale_y_continuous(breaks = pretty_breaks(5))", tags: ["axis","breaks","ggplot"] },
  { cat: "scales", fn: "alpha(colour, alpha)", desc: "Add transparency to a color.", example: 'scales::alpha("steelblue", 0.5)', tags: ["color","transparency","opacity"] },
  { cat: "scales", fn: "rescale(x, to, from)", desc: "Linearly rescale a numeric vector into a new range.", example: "scales::rescale(x, to = c(0,1))", tags: ["normalize","scale","transform"] },
  { cat: "scales", fn: "squish(x, range)", desc: "Squish values outside a range to the nearest boundary rather than treating as NA.", example: "scales::squish(x, range = c(0,100))", tags: ["clip","bound","transform"] },
  { cat: "scales", fn: "hue_pal()(n)", desc: "Generate ggplot2's default evenly-spaced hue color palette.", example: "scales::hue_pal()(4)", tags: ["palette","color","default"] },
  { cat: "scales", fn: "viridis_pal(option)(n)", desc: "Generate n colors from a viridis palette (\"viridis\", \"magma\", \"plasma\", \"cividis\").", example: 'scales::viridis_pal(option = "plasma")(5)', tags: ["palette","color","viridis"] },
  { cat: "scales", fn: "brewer_pal(type, palette)(n)", desc: "Generate n colors from a ColorBrewer palette.", example: 'scales::brewer_pal(palette = "Set2")(5)', tags: ["palette","color","brewer"] },
  { cat: "scales", fn: "muted(colour)", desc: "Produce a muted/darker version of a color, often used for diverging scale endpoints.", example: 'scales::muted("red")', tags: ["color","adjust"] },
  { cat: "scales", fn: "oob_squish / oob_censor", desc: "Out-of-bounds handling strategies used by scale_*(oob = ...) — squish clamps, censor turns to NA.", example: "scale_fill_gradient(limits = c(0,10), oob = scales::squish)", tags: ["ggplot","limits","clip"] },

  // ---------------- tidyverse misc ----------------
  { cat: "tidyverse", fn: "map(.x, .f) / map_dbl() / map_chr() / map_df()", desc: "purrr's type-stable apply functions — like lapply but consistent output types.", example: "map_dbl(1:5, ~ .x^2)", tags: ["purrr","apply","functional","loop"] },
  { cat: "tidyverse", fn: "~ .x (purrr lambda shorthand)", desc: "Anonymous function shorthand used inside purrr map functions.", example: "map(df_list, ~ nrow(.x))", tags: ["purrr","function","lambda"] },
  { cat: "tidyverse", fn: "tibble(...)", desc: "Create a modern data frame (tibble) with nicer printing and stricter behavior.", example: 'tibble(x = 1:3, y = c("a","b","c"))', tags: ["dataframe","create","tibble"] },
  { cat: "tidyverse", fn: "as_tibble(x)", desc: "Convert a data frame/matrix/list into a tibble.", example: "as_tibble(mtcars)", tags: ["convert","tibble","dataframe"] },
  { cat: "tidyverse", fn: "glimpse(x)", desc: "Transposed, colorized structure preview — tidyverse's version of str().", example: "glimpse(mtcars)", tags: ["inspect","explore","structure"] },
  { cat: "tidyverse", fn: "read_csv(file) / write_csv(x, file)", desc: "readr's faster, more consistent CSV import/export (returns a tibble, keeps strings as-is).", example: 'df <- read_csv("data.csv")', tags: ["import","export","csv","io"] },
  { cat: "tidyverse", fn: "read_excel(path, sheet) [readxl]", desc: "Read an Excel spreadsheet into a data frame.", example: 'readxl::read_excel("data.xlsx", sheet = 1)', tags: ["import","excel","io"] },
  { cat: "tidyverse", fn: "%>% / |> (pipe)", desc: "Pipe the left-hand result into the first argument of the right-hand function. |> is base R's native pipe; %>% is magrittr's (used throughout tidyverse).", example: "df %>% filter(age > 21) %>% summarise(n = n())", tags: ["pipe","chain","syntax"] },
  { cat: "tidyverse", fn: "here::here(...)", desc: "Build file paths relative to the project root, avoiding fragile setwd() calls.", example: 'read_csv(here::here("data", "raw.csv"))', tags: ["path","file","project"] },

  // ---------------- forcats ----------------
  { cat: "forcats", fn: "fct_reorder(f, x, .fun = median)", desc: "Reorder factor levels by another variable — fixes bars/lines plotting in a meaningless order.", example: "mutate(df, category = fct_reorder(category, value))", tags: ["reorder","factor","ggplot","order"] },
  { cat: "forcats", fn: "fct_infreq(f)", desc: "Reorder factor levels by descending frequency.", example: "fct_infreq(df$category)", tags: ["reorder","factor","frequency"] },
  { cat: "forcats", fn: "fct_rev(f)", desc: "Reverse the order of factor levels.", example: "fct_rev(df$category)", tags: ["reverse","factor","order"] },
  { cat: "forcats", fn: "fct_lump(f, n)", desc: "Lump the rarest levels together into an \"Other\" category, keeping the top n.", example: "fct_lump(df$category, n = 5)", tags: ["lump","other","collapse","factor"] },
  { cat: "forcats", fn: "fct_relevel(f, ...)", desc: "Manually move specific levels to the front (or a given position).", example: 'fct_relevel(df$grade, "Low", "Mid", "High")', tags: ["reorder","factor","manual"] },
  { cat: "forcats", fn: "fct_recode(f, ...)", desc: "Rename factor levels by hand, new = old.", example: 'fct_recode(df$sex, "Male" = "M", "Female" = "F")', tags: ["rename","recode","factor"] },
  { cat: "forcats", fn: "fct_collapse(f, ...)", desc: "Group several existing levels into one new level.", example: 'fct_collapse(df$state, West = c("CA","OR","WA"))', tags: ["collapse","group","factor","recode"] },
  { cat: "forcats", fn: "fct_drop(f)", desc: "Drop unused (zero-count) factor levels.", example: "fct_drop(df$category)", tags: ["drop","unused","factor","clean"] },
  { cat: "forcats", fn: "fct_explicit_na(f, na_level)", desc: "Give NA values their own explicit factor level instead of silently dropping them.", example: 'fct_explicit_na(df$category, na_level = "(Missing)")', tags: ["missing","na","factor"] },
  { cat: "forcats", fn: "fct_count(f)", desc: "Count observations in each factor level (like table(), but returns a tibble).", example: "fct_count(df$category)", tags: ["count","tabulate","factor"] },
  { cat: "forcats", fn: "as_factor(x)", desc: "Convert to factor preserving order of first appearance, unlike base as.factor() which sorts alphabetically.", example: "as_factor(df$category)", tags: ["convert","factor","order"] },
  { cat: "forcats", fn: "fct_unify(fs)", desc: "Standardize levels across a list of factors so they all share the same set.", example: "fct_unify(list(df1$grp, df2$grp))", tags: ["combine","factor","levels"] },

  // ---------------- Stats & modeling (base R) ----------------
  { cat: "stats", fn: "lm(formula, data)", desc: "Fit a linear regression model.", example: "model <- lm(mpg ~ wt + hp, data = mtcars)", tags: ["regression","linear model","fit"] },
  { cat: "stats", fn: "glm(formula, family, data)", desc: "Fit a generalized linear model (e.g. logistic regression with family = binomial).", example: 'glm(passed ~ hours, data = df, family = binomial)', tags: ["logistic","regression","glm"] },
  { cat: "stats", fn: "summary(model)", desc: "View a fitted model's coefficients, standard errors, p-values, and R-squared.", example: "summary(model)", tags: ["model","output","coefficients"] },
  { cat: "stats", fn: "predict(model, newdata)", desc: "Generate predictions from a fitted model on new data.", example: "predict(model, newdata = test_df)", tags: ["predict","forecast","model"] },
  { cat: "stats", fn: "residuals(model) / resid(model)", desc: "Extract a model's residuals (observed minus fitted).", example: "residuals(model)", tags: ["residuals","diagnostics","model"] },
  { cat: "stats", fn: "fitted(model)", desc: "Extract a model's fitted (predicted) values for the training data.", example: "fitted(model)", tags: ["fitted","predicted","model"] },
  { cat: "stats", fn: "coef(model)", desc: "Extract a model's estimated coefficients.", example: "coef(model)", tags: ["coefficients","model"] },
  { cat: "stats", fn: "confint(model)", desc: "Confidence intervals for a model's coefficients.", example: "confint(model, level = 0.95)", tags: ["confidence interval","model"] },
  { cat: "stats", fn: "anova(model1, model2)", desc: "Compare nested models, or produce an ANOVA table for a single model.", example: "anova(small_model, big_model)", tags: ["anova","compare","model"] },
  { cat: "stats", fn: "aov(formula, data)", desc: "Fit an analysis-of-variance model.", example: "aov(score ~ group, data = df)", tags: ["anova","fit","group comparison"] },
  { cat: "stats", fn: "t.test(x, y)", desc: "One-sample or two-sample t-test for comparing means.", example: "t.test(df$score ~ df$group)", tags: ["t-test","hypothesis test","compare means"] },
  { cat: "stats", fn: "cor(x, y) / cor.test(x, y)", desc: "Correlation coefficient, and a test of its significance.", example: "cor.test(df$x, df$y)", tags: ["correlation","test"] },
  { cat: "stats", fn: "chisq.test(x)", desc: "Chi-squared test of independence/goodness of fit on a table.", example: "chisq.test(table(df$a, df$b))", tags: ["chi-squared","categorical","test"] },
  { cat: "stats", fn: "wilcox.test(x, y)", desc: "Non-parametric rank-based test (Mann-Whitney/Wilcoxon), an alternative to t.test.", example: "wilcox.test(df$score ~ df$group)", tags: ["nonparametric","test","rank"] },
  { cat: "stats", fn: "shapiro.test(x)", desc: "Test whether a sample looks normally distributed.", example: "shapiro.test(df$residuals)", tags: ["normality","test","assumption"] },
  { cat: "stats", fn: "AIC(model) / BIC(model)", desc: "Information criteria for comparing model fit vs. complexity (lower is better).", example: "AIC(model1, model2)", tags: ["model selection","compare","criteria"] },
  { cat: "stats", fn: "step(model)", desc: "Stepwise variable selection by AIC (forward/backward/both).", example: 'step(model, direction = "both")', tags: ["stepwise","model selection","variables"] },
  { cat: "stats", fn: "y ~ x1 + x2 (formula syntax)", desc: "R's formula notation: response ~ predictors. Use * for main effects + interaction, : for interaction only, - to remove a term.", example: "mpg ~ wt * hp", tags: ["formula","syntax","model"] },

  // ---------------- broom ----------------
  { cat: "broom", fn: "tidy(model)", desc: "Turn a model's coefficients into a tidy data frame (term, estimate, std.error, p.value).", example: "tidy(model)", tags: ["model","output","tidy","coefficients"] },
  { cat: "broom", fn: "tidy(model, conf.int = TRUE)", desc: "Same as tidy(), plus confidence interval columns for each term.", example: "tidy(model, conf.int = TRUE)", tags: ["model","confidence interval","tidy"] },
  { cat: "broom", fn: "glance(model)", desc: "One-row summary of overall model fit (R-squared, AIC, BIC, p-value, etc).", example: "glance(model)", tags: ["model","summary","fit","r-squared"] },
  { cat: "broom", fn: "augment(model, data)", desc: "Append fitted values, residuals, and diagnostics (like .cooksd) onto the original data.", example: "augment(model, data = mtcars)", tags: ["model","diagnostics","residuals","fitted"] },

  // ---------------- janitor ----------------
  { cat: "janitor", fn: "clean_names(dat)", desc: "Convert all column names to consistent snake_case, stripping spaces/punctuation.", example: "clean_names(df)", tags: ["names","clean","columns","snake_case"] },
  { cat: "janitor", fn: "tabyl(dat, var1, var2)", desc: "Frequency table (1-way or 2-way) that returns a tidy data frame — nicer than base table().", example: "tabyl(df, category)", tags: ["frequency","table","count"] },
  { cat: "janitor", fn: "adorn_totals(dat, where)", desc: "Add row and/or column totals to a tabyl summary.", example: 'tabyl(df, a, b) %>% adorn_totals(c("row","col"))', tags: ["totals","table","summary"] },
  { cat: "janitor", fn: "adorn_percentages(dat, denominator)", desc: "Convert a tabyl's counts into row/column/total percentages.", example: 'tabyl(df, a, b) %>% adorn_percentages("row")', tags: ["percent","table","proportion"] },
  { cat: "janitor", fn: "get_dupes(dat, ...)", desc: "Find and return all rows that are duplicates on specified key columns.", example: "get_dupes(df, id)", tags: ["duplicates","find","clean"] },
  { cat: "janitor", fn: "remove_empty(dat, which)", desc: "Drop entirely empty rows and/or columns.", example: 'remove_empty(df, which = c("rows","cols"))', tags: ["empty","clean","drop"] },
  { cat: "janitor", fn: "remove_constant(dat)", desc: "Drop columns that only contain one unique value.", example: "remove_constant(df)", tags: ["constant","clean","drop","columns"] },
  { cat: "janitor", fn: "round_half_up(x, digits)", desc: "Rounds .5 values up consistently, fixing base R round()'s banker's-rounding surprise.", example: "round_half_up(2.5)", tags: ["round","number","fix"] },
  { cat: "janitor", fn: "excel_numeric_to_date(x)", desc: "Convert Excel's numeric date serial values into proper Date objects.", example: "excel_numeric_to_date(44197)", tags: ["excel","date","convert"] },
  { cat: "janitor", fn: "compare_df_cols(...)", desc: "Compare column names and types across multiple data frames — handy before bind_rows().", example: "compare_df_cols(df1, df2)", tags: ["compare","columns","dataframe"] },

  // ---------------- tidytext ----------------
  { cat: "tidytext", fn: "unnest_tokens(output, input, token)", desc: "Split text into one-token-per-row (words, ngrams, sentences, etc).", example: 'unnest_tokens(df, word, text)', tags: ["tokenize","text","words"] },
  { cat: "tidytext", fn: "unnest_tokens(..., token = \"ngrams\", n = 2)", desc: "Tokenize into n-grams (e.g. bigrams) instead of single words.", example: 'unnest_tokens(df, bigram, text, token = "ngrams", n = 2)', tags: ["ngram","bigram","tokenize"] },
  { cat: "tidytext", fn: "get_stopwords() / stop_words", desc: "Built-in stopword lexicons for filtering out common low-information words.", example: "anti_join(word_df, stop_words)", tags: ["stopwords","filter","text cleaning"] },
  { cat: "tidytext", fn: "anti_join(data, stop_words)", desc: "Common pattern to remove stopwords after unnest_tokens().", example: "df %>% unnest_tokens(word, text) %>% anti_join(stop_words)", tags: ["stopwords","clean","text"] },
  { cat: "tidytext", fn: "bind_tf_idf(data, term, document, n)", desc: "Compute term frequency-inverse document frequency to find words distinctive to each document.", example: "bind_tf_idf(word_counts, word, document, n)", tags: ["tf-idf","text mining","weighting"] },
  { cat: "tidytext", fn: "get_sentiments(lexicon)", desc: "Load a sentiment lexicon (\"bing\", \"afinn\", \"nrc\", \"loughran\") for sentiment analysis.", example: 'get_sentiments("bing")', tags: ["sentiment","lexicon","text"] },
  { cat: "tidytext", fn: "inner_join(word_df, get_sentiments(...))", desc: "Common pattern to attach sentiment scores to tokenized words.", example: 'df %>% unnest_tokens(word, text) %>% inner_join(get_sentiments("bing"))', tags: ["sentiment","join","text analysis"] },
  { cat: "tidytext", fn: "cast_dtm(data, document, term, value) / cast_sparse(...)", desc: "Convert tidy word-count data into a document-term matrix for topic modeling etc.", example: "cast_dtm(word_counts, document, word, n)", tags: ["document-term matrix","topic modeling","convert"] },
  { cat: "tidytext", fn: "count(data, document, word, sort = TRUE)", desc: "Common dplyr pattern after tokenizing: count word frequency per document.", example: "df %>% unnest_tokens(word, text) %>% count(document, word, sort = TRUE)", tags: ["count","frequency","word"] },

  // ---------------- knitr ----------------
  { cat: "knitr", fn: "knit(input)", desc: "Render an R Markdown/Rnw source file into its output document.", example: 'knitr::knit("report.Rmd")', tags: ["render","report","rmarkdown"] },
  { cat: "knitr", fn: "kable(x, format, digits, col.names)", desc: "Format a data frame as a simple, clean table for HTML/PDF/Word reports.", example: 'knitr::kable(df, digits = 2, caption = "Results")', tags: ["table","report","format"] },
  { cat: "knitr", fn: "opts_chunk$set(...)", desc: "Set global default chunk options (echo, warning, message, fig.width, etc.) for the whole document.", example: "knitr::opts_chunk$set(echo = FALSE, warning = FALSE)", tags: ["chunk","options","rmarkdown"] },
  { cat: "knitr", fn: "include_graphics(path)", desc: "Embed an external image file in a knitted report.", example: 'knitr::include_graphics("figures/plot.png")', tags: ["image","embed","report"] },
  { cat: "knitr", fn: "read_chunk(path)", desc: "Import labeled code chunks from an external .R script to reuse in a report.", example: 'knitr::read_chunk("analysis.R")', tags: ["chunk","external","reuse"] },
  { cat: "knitr", fn: "purl(input)", desc: "Extract just the R code from an Rmd file into a plain .R script.", example: 'knitr::purl("report.Rmd")', tags: ["extract","code","script"] },
  { cat: "knitr", fn: "```{r chunk-name, echo=FALSE}", desc: "Chunk header syntax: label the chunk, then set per-chunk options like echo/eval/warning/fig.height.", example: "```{r plot1, echo=FALSE, fig.height=4}", tags: ["chunk","syntax","rmarkdown"] },

  // ---------------- plotly ----------------
  { cat: "plotly", fn: "plot_ly(data, x, y, type, mode)", desc: "Create an interactive plot directly (scatter, bar, line, etc), independent of ggplot2.", example: 'plot_ly(mtcars, x = ~wt, y = ~mpg, type = "scatter", mode = "markers")', tags: ["interactive","plot","create"] },
  { cat: "plotly", fn: "ggplotly(p)", desc: "Convert an existing ggplot2 plot into an interactive, zoomable/hoverable plotly plot.", example: "ggplotly(ggplot(mtcars, aes(wt, mpg)) + geom_point())", tags: ["ggplot2","convert","interactive"] },
  { cat: "plotly", fn: "add_trace(p, ...) / add_markers() / add_lines() / add_bars()", desc: "Add another data layer (trace) to an existing plotly object.", example: 'plot_ly(df, x = ~date) %>% add_lines(y = ~actual) %>% add_lines(y = ~forecast)', tags: ["layer","trace","add"] },
  { cat: "plotly", fn: "layout(p, title, xaxis, yaxis, legend)", desc: "Customize a plotly plot's title, axis settings, legend, and overall layout.", example: 'layout(p, title = "MPG vs Weight", xaxis = list(title = "Weight"))', tags: ["title","axis","legend","customize"] },
  { cat: "plotly", fn: "subplot(..., nrows)", desc: "Combine multiple plotly plots into one figure, arranged in a grid.", example: "subplot(p1, p2, nrows = 2)", tags: ["combine","grid","multiple plots"] },
  { cat: "plotly", fn: "config(p, displayModeBar = FALSE)", desc: "Configure the plot's interactivity/toolbar options (e.g. hide the mode bar, disable zoom).", example: "config(p, displayModeBar = FALSE)", tags: ["config","toolbar","options"] },
  { cat: "plotly", fn: "toWebGL(p)", desc: "Convert an SVG-based plotly plot to WebGL rendering for better performance on large datasets.", example: "toWebGL(p)", tags: ["performance","webgl","large data"] },
  { cat: "plotly", fn: "animation_opts(p, frame, transition)", desc: "Control animation timing when a plot has a frame aesthetic (e.g. animating over time/year).", example: "animation_opts(p, frame = 1000, transition = 500)", tags: ["animation","frame","time"] },
  { cat: "plotly", fn: "highlight(p, on, off)", desc: "Enable linked brushing/highlighting of points across multiple coordinated plots.", example: 'highlight(p, on = "plotly_hover")', tags: ["highlight","brushing","linked plots"] },
  { cat: "plotly", fn: "event_data(\"plotly_click\")", desc: "Capture interactive click/hover/selection events from a plot inside a Shiny app.", example: 'event_data("plotly_click", source = "myplot")', tags: ["shiny","event","interactive","click"] },
  { cat: "plotly", fn: "plotlyOutput(outputId) / renderPlotly({...})", desc: "Shiny UI/server pair for embedding a plotly plot in an app.", example: "output$plot <- renderPlotly({ plot_ly(df, x = ~x, y = ~y) })", tags: ["shiny","output","render"] },
  { cat: "plotly", fn: "save_image(p, file)", desc: "Export a plotly plot to a static image file (PNG, JPEG, PDF, SVG) — requires the kaleido engine.", example: 'save_image(p, "plot.png")', tags: ["export","save","image"] },
];
